In [4]:
import torch
import numpy as np

Пусть матрица признаков равна [[4, 2, -1],[-6, 0, 5],[3, 2, 2]], а ядро свертки -- [[0, 1, 2],[1, -1, 0],[1, 0, -2]]

Каков будет результат применения свертки со stride=2, padding=1?

In [35]:
padding = 1
stride = 2
x = np.array([[4, 2, -1],[-6, 0, 5],[3, 2, 2]])
x = np.pad(x, padding, "constant")
kernel = np.array([[0, 1, 2],[1, -1, 0],[1, 0, -2]])
x

array([[ 0,  0,  0,  0,  0],
       [ 0,  4,  2, -1,  0],
       [ 0, -6,  0,  5,  0],
       [ 0,  3,  2,  2,  0],
       [ 0,  0,  0,  0,  0]])

In [36]:
kernel

array([[ 0,  1,  2],
       [ 1, -1,  0],
       [ 1,  0, -2]])

In [41]:
for row in range(1, x.shape[0],  stride):
    for col in range(1, x.shape[1],  stride):
        print((x[row-1:row+2, col-1:col+2] * kernel).sum(), end=" ")
    print(',', end = " ")
        

-4 3 , -9 5 , 

In [42]:
import torch

from torch import nn

conv = nn.Conv2d(1,1,kernel_size=3, padding=1, stride=2, bias=False)

X = torch.FloatTensor([[[
    [4, 2, -1],
    [-6, 0, 5],
    [3, 2, 2]]]]
)

conv.weight.data = torch.FloatTensor([[[
    [0, 1, 2],
    [1, -1, 0],
    [1, 0, -2]]]]
)

res = conv(X).data[0,0]

print(res)

tensor([[-4.,  3.],
        [-9.,  5.]])
