In [1]:
import numpy as np
import torch

Допустим, у нас есть функция $f(X) = \sum{log_{e}(x_{ij} + 1)}$, где $X$ - тензор размера 2x2. Мы выбрали начальное приближение $X^{t=0} = [[1, 2], [4, 5]]$. И шаг градиентного спуска $\alpha=10$
  
Чему будет равен $X^{t=1}$ ? 

In [3]:
X = np.array([[1, 2], [4, 5]])
der_f = lambda x: 1 / (x + 1)
(X - 10 * der_f(X)).round(3)

array([[-4.   , -1.333],
       [ 2.   ,  3.333]])

Реализуйте расчет градиента для функции $f(w) = \prod\limits_{i,j}{log_{e}(log_{e}({w_{i,j} + 7}}))$ в точке $w = [[5, 10], [1, 2]]$

In [6]:
W = torch.tensor([[5, 10], [1, 2]], dtype=torch.float, requires_grad=True)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
W = W.to(device)
W.retain_grad()s

func = torch.log(torch.log(W + 7)).prod()

func.backward()

W.grad

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]], dtype=torch.float64)


Реализуйте градиентный спуск для той же функции.  
  
Пусть начальным приближением будет $w^{t=0} = [[5, 10], [1, 2]]$, шаг градиентного спуска $alpha=0.001$.

Чему будет равен $w^{t=500}$ ?

In [18]:
import torch


w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
w = w.to(device)
w.retain_grad()

for _ in range(500):
    function = (w + 7).log().log().prod()
    function.backward()
    w.data -=  alpha * w.grad
    w.grad.zero_()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)


Перепишите пример, используя torch.optim.SGD

In [19]:
import torch


w = torch.tensor([[5., 10.], [1., 2.]], requires_grad=True)
alpha = 0.001
optimizer =  torch.optim.SGD([w], lr=0.001)

for _ in range(500):
    function = (w + 7).log().log().prod()
    function.backward()
    optimizer.step()
    optimizer.zero_grad()

print(w)

tensor([[4.9900, 9.9948],
        [0.9775, 1.9825]], requires_grad=True)
