In [1]:
matrix(1:10, nrow = 2, ncol = 2)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [2]:
matrix(1:10, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [3]:
matrix(1:10, nrow = 2, byrow = T)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [5]:
n <- matrix(1:10, ncol =  2)
dim(n)
n

[1] 5 2

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [6]:
m1 = matrix(1:4, nrow = 2 )
m2 = matrix(c(1, 2, 2, 3), nrow = 2)

In [7]:
m1 + m2

[,1] [,2]
[1,] 2    5   
[2,] 4    7

In [8]:
m1 + 4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [12]:
# multiplication by linear algebra
print(m1 %*% m2)

# not linear
print(m1 * m2)


     [,1] [,2]
[1,]    7   11
[2,]   10   16
     [,1] [,2]
[1,]    1    6
[2,]    4   12


In [13]:
m1[1, 1]

[1] 1

In [20]:
print(m1[1, ])
print(m1[1,, drop = F])
asd 

[1] 1 3
     [,1] [,2]
[1,]    1    3


In [19]:
print(m1[, 1])
print(m1[, 1, drop = F])

[1] 1 2
     [,1]
[1,]    1
[2,]    2
