In [1]:
matrix(1:10, nrow = 2, ncol = 2)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [2]:
matrix(1:10, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [3]:
matrix(1:10, nrow = 2, byrow = T)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [5]:
n <- matrix(1:10, ncol =  2)
dim(n)
n

[1] 5 2

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [36]:
m1 = matrix(1:4, nrow = 2 )
m2 = matrix(c(1, 2, 2, 3), nrow = 2)

In [7]:
m1 + m2

[,1] [,2]
[1,] 2    5   
[2,] 4    7

In [8]:
m1 + 4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [12]:
# multiplication by linear algebra
print(m1 %*% m2)

# not linear
print(m1 * m2)


     [,1] [,2]
[1,]    7   11
[2,]   10   16
     [,1] [,2]
[1,]    1    6
[2,]    4   12


In [13]:
m1[1, 1]

[1] 1

In [37]:
print(m1[1, ])
print(m1[1,, drop = F])

[1] 1 3
     [,1] [,2]
[1,]    1    3


In [19]:
print(m1[, 1])
print(m1[, 1, drop = F])

[1] 1 2
     [,1]
[1,]    1
[2,]    2


___

Если матрица mat имеет размерность m на n (например, mat <- matrix(0, m, n)), то какой объект будет возвращён после выполнения следующих операций?

In [3]:
m = 5
n = 6
mat = matrix(1:30, m, n)
mat

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     6   11   16   21   26  
[2,] 2     7   12   17   22   27  
[3,] 3     8   13   18   23   28  
[4,] 4     9   14   19   24   29  
[5,] 5    10   15   20   25   30

In [10]:
print(mat[m,])

[1]  5 10 15 20 25 30


In [9]:
print(mat[m, , drop = FALSE])

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    5   10   15   20   25   30


In [11]:
print(mat > 5)

      [,1] [,2] [,3] [,4] [,5] [,6]
[1,] FALSE TRUE TRUE TRUE TRUE TRUE
[2,] FALSE TRUE TRUE TRUE TRUE TRUE
[3,] FALSE TRUE TRUE TRUE TRUE TRUE
[4,] FALSE TRUE TRUE TRUE TRUE TRUE
[5,] FALSE TRUE TRUE TRUE TRUE TRUE


In [12]:
print(mat[mat > 5])

 [1]  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30


___

Предположим, что у нас есть целочисленный вектор v и число n. Наша задача — найти позицию элемента в векторе, который ближе всего к числу n. При этом если таких элементов несколько, необходимо указать все позиции.

Напишите функцию, которая принимает на вход вектор и число и возвращает вектор индексов, отвечающих указанному условию. Индексы должны быть выстроены по возрастанию.

Пример. Пусть v <- c(5, 2, 7, 7, 7, 2, 0, 0) и n = 1. Ответом будет вектор

2 6 7 8

Подсказки: 
- "ближе всего" означает минимальную разницу между числами;
- не забудьте про модуль!

In [32]:
find_closest <- function(v, n) {
    return(
        which(
            abs(v - n) == min(v - n)
        )
    )
}

In [33]:
v <- c(5, 2, 7, 7, 7, 2, 0, 0) 
n = 1
print(find_closest(v, n))

[1] 2 6 7 8


___

Построим зиккурат! Напишите функцию, которая принимает одно целое число n, а возвращает “ступенчатую” матрицу, состоящую из n этажей. Этажи нумеруются с первого, ширина каждой ступеньки равна одной строке или столбцу.

Пример. Пусть n=4, тогда необходимо вернуть матрицу вида

-  1   1   1   1   1   1   1
-  1   2   2   2   2   2   1
-  1   2   3   3   3   2   1
-  1   2   3   4   3   2   1
-  1   2   3   3   3   2   1
-  1   2   2   2   2   2   1
-  1   1   1   1   1   1   1

Подсказка: обратите внимание на случай n=1! Зиккурат в этом случае будет матрицей 1 на 1, высотой 1.

In [34]:
build_ziggurat <- function(n) {
    matr  <- matrix(0, ncol = n*2-1, nrow = n*2-1)
    matr[(n*2+1)/2, (n*2+1)/2] = n
    for(i in 1:(n*2-1)) {
        for(j in 1:(n*2-1)) {
            x = abs(n - i)
            y = abs(n - j)
            matr[i, j] = n - max(x,y)
        }
    }
    return(matr)
}

build_ziggurat_1 <- function(n) {
    n2 <- n * 2 - 1
    m <- matrix(0L, ncol = n2, nrow = n2)
    n - pmax(abs(n - row(m)), abs(n - col(m)))
}
build_ziggurat_1(2)

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    2    1   
[3,] 1    1    1

In [31]:
?pmin

___
Для работы с матрицами пригодится функция под названием diag. Примечательно, что эта функция возвращает принципиально разные объекты в зависимости от аргумента. Какие именно?

P.S. Единичная матрица -- это не та, которая состоит из единиц. Единицы у неё только на диагонали, а остальные элементы равны нулю.

In [36]:
diag(5)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    0    0    0    0   
[2,] 0    1    0    0    0   
[3,] 0    0    1    0    0   
[4,] 0    0    0    1    0   
[5,] 0    0    0    0    1

In [37]:
diag(c(1,2,3))

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

In [38]:
diag(matrix(1:9, ncol = 3))

[1] 1 5 9

___
Если вектор достаточно длинный, то визуально сложно оценить, какие в нём содержатся элементы и сколько раз они повторяются. В этом случае полезно будет посмотреть на таблицу частот элементов.

Пусть x -- целочисленный вектор. Напишите функцию, которая вернёт матрицу из двух строк. В первой строке перечислите все различные элементы вектора, упорядоченные по возрастанию. Во второй строке укажите частоты (количество повторов) этих элементов.

Пример. Пусть x <- c(5, 2, 7, 7, 7, 2, 0, 0). Тогда функция должна вернуть матрицу 2х4 с элементами

0 2 5 7  
2 2 1 3

In [190]:
count_elements <- function(x) {
    uni  <- sort(unique(x))
    name  <- rep(0, length(uni))
    names(name)  <- uni
    for(i in x) {
        elem = toString(i)
        name[elem]  <- name[elem] + 1
    }
    matr  <- matrix(uni, nrow = 1)
    matr  <- rbind(matr, name)
    return(matr)
}

x <- c(5, 2, 7, 7, 7, 2, 0, 0)
count_elements(x)


0 2 5 7
     0 2 5 7
name 2 2 1 3

In [189]:
x <- sample(10, 10000, replace = T)
microbenchmark(count_elements(x), table(x), times = 10)

expr              time     
1  table(x)             806305
2  count_elements(x) 104736187
3  count_elements(x) 103375406
4  table(x)             749795
5  count_elements(x) 104449088
6  table(x)             751313
7  table(x)             663325
8  count_elements(x) 108051291
9  table(x)             817683
10 table(x)             663324
11 table(x)             654981
12 count_elements(x) 103335584
13 table(x)             768759
14 count_elements(x) 105837556
15 count_elements(x) 105503429
16 table(x)             761932
17 count_elements(x) 109340393
18 table(x)             765345
19 count_elements(x) 108682379
20 count_elements(x) 108837495

In [191]:
count_elements <- function(x) {
  v <- sort(unique(x))
  rbind(v, sapply(v, function(i) sum(x == i)))
}

In [194]:
x <- sample(10, 10000, replace = T)
microbenchmark(count_elements(x), table(x), times = 10)


expr              time  
1  table(x)          850299
2  table(x)          698975
3  count_elements(x) 583300
4  count_elements(x) 539306
5  count_elements(x) 537790
6  count_elements(x) 534376
7  table(x)          675840
8  table(x)          669393
9  table(x)          665980
10 table(x)          664842
11 count_elements(x) 542720
12 count_elements(x) 536272
13 table(x)          668635
14 table(x)          687597
15 count_elements(x) 533238
16 count_elements(x) 553339
17 count_elements(x) 520723
18 table(x)          675840
19 count_elements(x) 533618
20 table(x)          680391

___
Парижане бунтуют! По слухам, Бастилия плохо охраняется, а её арсеналы полны пороха и мушкетов.
Пришло время решительных действий. Наши агенты смогли подсчитать количество солдат в патрулях в каждой из восьми башен крепости. Вот эти данные:

Составьте короткий отчёт: какая из башен менее всего защищена, сколько в ней солдат, и сколько всего солдат в Бастилии? Свобода, равенство, братство!

P.S. Формат ответа: tower_name, XX, YY: полное название башни как в списке (без кавычек) и два числа. В качестве разделителя -- запятая и пробел.

In [222]:
set.seed(1789)
bastille <- list(
  "La Chapelle Tower" = rbinom(5, 10, 1/2), 
  "Tresor Tower" = rbinom(8, 12, 1/4), 
  "Comte Tower" = rbinom(14, 3, 1/5) + 1,
  "Baziniere Tower" = rbinom(8, 4, 4/5), 
  "Bertaudiere Tower" = rbinom(4, 8, 2/3),
  "Liberte Tower" = rbinom(1, 100, 0.1), 
  "Puits Tower" = rbinom(5, 5, 0.7),
  "Coin Tower" = rbinom(3, 16, 0.4)
)
all_n  <- 0
max_n  <- 9999999
name  <- ""
for(i in names(bastille)) {
    some  <- sum(c(bastille[[i]]))
    all_n  <- all_n + some
    if (some < max_n) {
        name  <- i
        max_n  <- some
    }
}
print(name)
print(max_n)
print(all_n)

[1] "Liberte Tower"
[1] 10
[1] 170


In [223]:
b <- sapply(bastille, sum)
b
paste(c(names(which.min(b)), min(b), sum(b)), collapse = ", ")

La Chapelle Tower      Tresor Tower       Comte Tower   Baziniere Tower 
               28                30                23                24 
Bertaudiere Tower     Liberte Tower       Puits Tower        Coin Tower 
               18                10                20                17

[1] "Liberte Tower, 10, 170"