In [1]:
matrix(1:10, nrow = 2, ncol = 2)

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [2]:
matrix(1:10, nrow = 2)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    3    5    7     9  
[2,] 2    4    6    8    10

In [3]:
matrix(1:10, nrow = 2, byrow = T)

[,1] [,2] [,3] [,4] [,5]
[1,] 1    2    3    4     5  
[2,] 6    7    8    9    10

In [5]:
n <- matrix(1:10, ncol =  2)
dim(n)
n

[1] 5 2

[,1] [,2]
[1,] 1     6  
[2,] 2     7  
[3,] 3     8  
[4,] 4     9  
[5,] 5    10

In [36]:
m1 = matrix(1:4, nrow = 2 )
m2 = matrix(c(1, 2, 2, 3), nrow = 2)

In [7]:
m1 + m2

[,1] [,2]
[1,] 2    5   
[2,] 4    7

In [8]:
m1 + 4

[,1] [,2]
[1,] 5    7   
[2,] 6    8

In [12]:
# multiplication by linear algebra
print(m1 %*% m2)

# not linear
print(m1 * m2)


     [,1] [,2]
[1,]    7   11
[2,]   10   16
     [,1] [,2]
[1,]    1    6
[2,]    4   12


In [13]:
m1[1, 1]

[1] 1

In [37]:
print(m1[1, ])
print(m1[1,, drop = F])

[1] 1 3
     [,1] [,2]
[1,]    1    3


In [19]:
print(m1[, 1])
print(m1[, 1, drop = F])

[1] 1 2
     [,1]
[1,]    1
[2,]    2


___

Если матрица mat имеет размерность m на n (например, mat <- matrix(0, m, n)), то какой объект будет возвращён после выполнения следующих операций?

In [3]:
m = 5
n = 6
mat = matrix(1:30, m, n)
mat

[,1] [,2] [,3] [,4] [,5] [,6]
[1,] 1     6   11   16   21   26  
[2,] 2     7   12   17   22   27  
[3,] 3     8   13   18   23   28  
[4,] 4     9   14   19   24   29  
[5,] 5    10   15   20   25   30

In [10]:
print(mat[m,])

[1]  5 10 15 20 25 30


In [9]:
print(mat[m, , drop = FALSE])

     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    5   10   15   20   25   30


In [11]:
print(mat > 5)

      [,1] [,2] [,3] [,4] [,5] [,6]
[1,] FALSE TRUE TRUE TRUE TRUE TRUE
[2,] FALSE TRUE TRUE TRUE TRUE TRUE
[3,] FALSE TRUE TRUE TRUE TRUE TRUE
[4,] FALSE TRUE TRUE TRUE TRUE TRUE
[5,] FALSE TRUE TRUE TRUE TRUE TRUE


In [12]:
print(mat[mat > 5])

 [1]  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30


___

Предположим, что у нас есть целочисленный вектор v и число n. Наша задача — найти позицию элемента в векторе, который ближе всего к числу n. При этом если таких элементов несколько, необходимо указать все позиции.

Напишите функцию, которая принимает на вход вектор и число и возвращает вектор индексов, отвечающих указанному условию. Индексы должны быть выстроены по возрастанию.

Пример. Пусть v <- c(5, 2, 7, 7, 7, 2, 0, 0) и n = 1. Ответом будет вектор

2 6 7 8

Подсказки: 
- "ближе всего" означает минимальную разницу между числами;
- не забудьте про модуль!

In [32]:
find_closest <- function(v, n) {
    return(
        which(
            abs(v - n) == min(v - n)
        )
    )
}

In [33]:
v <- c(5, 2, 7, 7, 7, 2, 0, 0) 
n = 1
print(find_closest(v, n))

[1] 2 6 7 8


___

Построим зиккурат! Напишите функцию, которая принимает одно целое число n, а возвращает “ступенчатую” матрицу, состоящую из n этажей. Этажи нумеруются с первого, ширина каждой ступеньки равна одной строке или столбцу.

Пример. Пусть n=4, тогда необходимо вернуть матрицу вида

-  1   1   1   1   1   1   1
-  1   2   2   2   2   2   1
-  1   2   3   3   3   2   1
-  1   2   3   4   3   2   1
-  1   2   3   3   3   2   1
-  1   2   2   2   2   2   1
-  1   1   1   1   1   1   1

Подсказка: обратите внимание на случай n=1! Зиккурат в этом случае будет матрицей 1 на 1, высотой 1.

In [48]:
x = -1:1
y = -1:1

outer(x, y, FUN = "+")

[,1] [,2] [,3]
[1,] -2   -1   0   
[2,] -1    0   1   
[3,]  0    1   2