In [1]:
import numpy as np

Теперь давайте попробуем применить наши новые матричные формулы — сначала на игрушечном примере, который мы рассматривали пару видео назад.

У нас есть набор данных: знания о длине тормозного пути и скорости для трёх автомобилей.

$$ \begin{pmatrix} D & V \\ \hline 10 & 60 \\ 7 & 50 \\ 12 & 75\end{pmatrix} $$
 
Напишите через запятую оценки коэффициентов линейной регрессии $D$ на $V$, т.е. $\hat{\beta_0}$, $\hat{\beta_1}$ для модели $D=\beta_0+\beta_1\cdot V+\varepsilon\cdot D$ с точностью до трёх знаков после точки.

In [63]:
data = np.array(
    [[1, 10, 60],
     [1, 7, 50],
     [1, 12, 75]
    ]
)
data

array([[ 1, 10, 60],
       [ 1,  7, 50],
       [ 1, 12, 75]])

In [9]:
X = data[:, (0, 2)]
y = data[:, 1]
X, y

(array([[ 1, 60],
        [ 1, 50],
        [ 1, 75]]), array([10,  7, 12]))

$$ X \cdot \beta = y \rightarrow \beta = (X^T \cdot X)^{-1} \cdot X^T \cdot y$$

In [16]:
beta = np.linalg.inv(X.transpose().dot(X)).dot(X.transpose()).dot(y)
beta

array([-2.34210526,  0.19473684])

In [22]:
print(*np.round(beta, 4), sep=",")


-2.3421,0.1947


In [64]:
calc_weights(data[:, (0, 2)], data[:, 1])

array([-2.34210526,  0.19473684])

___
___

In [70]:
def calc_weights(X, y):
    return np.linalg.inv(X.transpose().dot(X)).dot(X.transpose()).dot(y)

Найдите оптимальные коэффициенты для построения линейной регрессии.

На вход вашему решению будет подано название csv-файла, из которого нужно считать данные. Пример можно посмотреть здесь. Загрузить их можно следующим образом:

Ваша задача — подсчитать вектор коэффициентов линейной регрессии для предсказания первой переменной (первого столбца данных) по всем остальным. Напомним, что модель линейной регрессии — это $ y = \beta_0 + \beta_1 x_1 + \cdots + \beta_n x_n$ 

Напечатайте коэффициенты линейной регрессии, начиная с $\beta_0$, через пробел. Мы будем проверять совпадения с точностью до 4 знаков после запятой.


In [69]:
import urllib
from urllib import request
import numpy as np


fname = input() or "https://stepic.org/media/attachments/lesson/16462/boston_houses.csv"
f = urllib.request.urlopen(fname)  
data = np.loadtxt(f, delimiter=',', skiprows=1)
y = np.copy(data[:, 0])
data[:, 0] = 1

print(*np.round(calc_weights(data, y), 4))


-3.6558 -0.2164 0.0737 4.4125 -25.4684 7.1432 -1.3011
