Создайте и напечатайте (с помощью функции print) массив класса np.ndarray ширины 4 и высоты 3 с двойками на главной диагонали и единицами на первой диагонали над главной, т.е. воплощение матрицы

$$ \begin{pmatrix}2 & 1 & 0 & 0 \\ 0 & 2 & 1 & 0 \\ 0 & 0 & 2 & 1 \end{pmatrix} $$



In [5]:
import numpy as np


mat = np.eye(3, 4, k=1) + np.eye(3, 4) * 2
mat

array([[2., 1., 0., 0.],
       [0., 2., 1., 0.],
       [0., 0., 2., 1.]])

Массив, который нужно было создать в предыдущей задаче, хранится в переменной mat. Превратите его в вертикальный вектор и напечатайте.

In [16]:
np.reshape(mat, (12,1))

array([[2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.],
       [0.],
       [0.],
       [0.],
       [2.],
       [1.]])

Задача: перемножьте две матрицы!

На вход программе подаются две матрицы, каждая в следующем формате: 
- на первой строке два целых положительных числа $n$ и $m$, разделенных пробелом - размерность матрицы. 
- В следующей строке находится $n \cdot m$ целых чисел, разделенных пробелами - элементы матрицы. Подразумевается, что матрица заполняется построчно, то есть первые $m$ чисел - первый ряд матрицы, числа от $m+1$ до $2 \cdot m$ - второй, и т.д.

Напечатайте произведение матриц $XY^T$, если они имеют подходящую форму, или строку "matrix shapes do not match", если формы матриц не совпадают должным образом. 

In [26]:
import numpy as np


def get_mats(vals=2):
    matrixes = [0] * vals
    for i in range(vals):
        row, col = map(int, input().split())
        matrixes[i] = np.reshape(
            list(map(int, input().split())),
            (row, col)
        )
    return matrixes
        
def mats_prod(X: np.array, Y: np.array):
    if X.shape[1] != Y.shape[1]:
        return "matrix shapes do not match"
    
    return np.dot(X, Y.transpose())

In [22]:
X, Y = get_mats()

2 3
8 7 7 14 4 6
4 3
5 5 1 5 2 6 3 3 9 1 4 6


In [27]:
mats_prod(X, Y)

array([[ 82,  96, 108,  78],
       [ 96, 114, 108,  66]])