In [142]:
import numpy as np


def search_w(X, y, epochs=None, w_0=None):
    """
    Реализация псевдокода из лекции
    """
    rows, cols = X.shape
    w = w_0 or np.zeros((cols, 1))
    perfect=False
    count = 0
    
    while not perfect:
        if count == epochs:
            break
        count += 1
        perfect = True
        
        for i in range(rows):
            pred = np.dot(X[i, :], w)[0] > 0
            target = y[i, :][0]
            # print(f"Предсказываем: {pred}, ожидаем {target}\n")
            
            e = X[i, :].reshape(cols, 1) 
            if pred != target:
                perfect = False
                sign = 1 if pred == 0 else -1
                w = w + sign * e
            # print("Матрица весов:")
            # print(w)
            # print("---------- \n")
    return w


Мы погуляли в фруктовом саду и собрали следующие данные про несколько обнаруженных там фруктов:

$$ \begin{array}{ c | c c c} & \text{желтизна} & \text{симметричность} & \text{это груша?} \\\hline 1 & 1 & 0.3 & \text{да} \\ 2 & 0.4 & 0.5 & \text{да} \\ 3 & 0.7 & 0.8 & \text{нет} \end{array} $$
 
Пусть у нас есть перцептрон с весами (0, 0) и смещением 0. 

Обучите его на приведённых данных различать груши и не груши (пока не надо обучать до сходимости: просто примените обучающее правило последовательно по одному разу на каждом примере, всего у вас получится 3 последовательных применения обучающего правила). 

Напишите в ответе через запятую получившиеся у вас смещение, вес для желтизны фрукта и вес для его симметричности (только итоговые, не надо писать результаты каждого шага).

In [144]:
X = np.array(
    [[1, 1, 0.3],
     [1, 0.4, 0.5],
     [1, 0.7, 0.8]
    ]
)
y = np.array([1, 1, 0]).reshape((3, 1))
print(X)
print(y)

[[1.  1.  0.3]
 [1.  0.4 0.5]
 [1.  0.7 0.8]]
[[1]
 [1]
 [0]]


In [145]:
search_w(X, y, 1)

1


array([[ 0. ],
       [ 0.3],
       [-0.5]])

In [126]:
print(*np.round(res.flatten(), 4), sep=",")

0.0,0.3,-0.5
